export const dots = [
  {
    src: 'images/dot.webp',
    width: '25',
    height: '25',
    left: '296',
    top: '135',
  },
  {
    src: 'images/dot.webp',
    width: '25',
    height: '25',
    left: '506',
    top: '135',
  },
  {
    src: 'images/dot.webp',
    width: '25',
    height: '25',
    left: '716',
    top: '135',
  },
  {
    src: 'images/dot.webp',
    width: '25',
    height: '25',
    left: '926',
    top: '135',
  },
  {
    src: 'images/dot.webp',
    width: '25',
    height: '25',
    left: '1241',
    top: '36',
  },
  {
    src: 'images/dot.webp',
    width: '25',
    height: '25',
    left: '1241',
    top: '233',
  },
  {
    src: 'images/dot.webp',
    width: '25',
    height: '25',
    left: '1556',
    top: '135',
  },
  {
    src: 'images/dot.webp',
    width: '25',
    height: '25',
    left: '1767',
    top: '135',
  },
  {
    src: 'images/dot.webp',
    width: '25',
    height: '25',
    left: '1976',
    top: '135',
  },
  {
    src: 'images/dot.webp',
    width: '25',
    height: '25',
    left: '2186',
    top: '135',
  },
];
