export const dots = [
  {
    src: '../../../assets/images/dot.png',
    width: '50px',
    height: '50px',
    left: '285px',
    top: '124px',
  },
  {
    src: '../../../assets/images/dot.png',
    width: '50px',
    height: '50px',
    left: '495px',
    top: '124px',
  },
  {
    src: '../../../assets/images/dot.png',
    width: '50px',
    height: '50px',
    left: '705px',
    top: '124px',
  },
  {
    src: '../../../assets/images/dot.png',
    width: '50px',
    height: '50px',
    left: '915px',
    top: '124px',
  },
  {
    src: '../../../assets/images/dot.png',
    width: '50px',
    height: '50px',
    left: '1230px',
    top: '25px',
  },
  {
    src: '../../../assets/images/dot.png',
    width: '50px',
    height: '50px',
    left: '1230px',
    top: '222px',
  },
  {
    src: '../../../assets/images/dot.png',
    width: '50px',
    height: '50px',
    left: '1545px',
    top: '124px',
  },
  {
    src: '../../../assets/images/dot.png',
    width: '50px',
    height: '50px',
    left: '1755px',
    top: '124px',
  },
  {
    src: '../../../assets/images/dot.png',
    width: '50px',
    height: '50px',
    left: '1965px',
    top: '124px',
  },
  {
    src: '../../../assets/images/dot.png',
    width: '50px',
    height: '50px',
    left: '2175px',
    top: '124px',
  },
];
