export const dots = [
  {
    src: '../../../assets/images/dot.png',
    width: '25px',
    height: '25px',
    left: '296px',
    top: '135px',
  },
  {
    src: '../../../assets/images/dot.png',
    width: '25px',
    height: '25px',
    left: '506px',
    top: '135px',
  },
  {
    src: '../../../assets/images/dot.png',
    width: '25px',
    height: '25px',
    left: '716px',
    top: '135px',
  },
  {
    src: '../../../assets/images/dot.png',
    width: '25px',
    height: '25px',
    left: '926px',
    top: '135px',
  },
  {
    src: '../../../assets/images/dot.png',
    width: '25px',
    height: '25px',
    left: '1241px',
    top: '36px',
  },
  {
    src: '../../../assets/images/dot.png',
    width: '25px',
    height: '25px',
    left: '1241px',
    top: '233px',
  },
  {
    src: '../../../assets/images/dot.png',
    width: '25px',
    height: '25px',
    left: '1556px',
    top: '135px',
  },
  {
    src: '../../../assets/images/dot.png',
    width: '25px',
    height: '25px',
    left: '1767px',
    top: '135px',
  },
  {
    src: '../../../assets/images/dot.png',
    width: '25px',
    height: '25px',
    left: '1976px',
    top: '135px',
  },
  {
    src: '../../../assets/images/dot.png',
    width: '25px',
    height: '25px',
    left: '2186px',
    top: '135px',
  },
];
