export const noteForms = [
  { _id: 201, label: 'Major', value: 'maj', disabled: false },
  { _id: 202, label: 'Minor', value: 'min', disabled: false },
  { _id: 203, label: 'Major 7th', value: 'maj7', disabled: false },
  { _id: 204, label: 'Minor 7th', value: 'min7', disabled: false },
  { _id: 205, label: 'Dominant 7th', value: '7', disabled: false },
  { _id: 206, label: 'Augmented', value: 'aug', disabled: false },
  { _id: 207, label: 'Diminished', value: 'dim', disabled: false },
  { _id: 208, label: 'Suspended 2nd', value: 'sus2', disabled: false },
  { _id: 209, label: 'Suspended 4th', value: 'sus4', disabled: false },
  { _id: 210, label: 'Major 6th', value: '6', disabled: false },
  { _id: 211, label: 'Minor 6th', value: 'min6', disabled: false },
  { _id: 212, label: '9th', value: '9', disabled: false },
  { _id: 213, label: 'Minor 9th', value: 'min9', disabled: false },
  { _id: 214, label: 'Major 9th', value: 'maj9', disabled: false },
  { _id: 215, label: '11th', value: '11', disabled: false },
  { _id: 216, label: '13th', value: '13', disabled: false },
  { _id: 217, label: '7#9', value: '7#9', disabled: false },
  { _id: 218, label: '7b9', value: '7b9', disabled: false },
  { _id: 219, label: 'Add9', value: 'add9', disabled: false },
  { _id: 220, label: '6/9', value: '6/9', disabled: false },
];
